### ISSUE TITLE
PHP warning (undefined variable: v) in WordPress

### ISSUE THREAD

**Issue by thegiorgiok** [rvalitov/widgetkit-slidesetlightbox#4]
Thanks for your effort, you did something that is missing!
The error is this:
Notice: Undefined variable: v in /home/wildaroma/public_html/wp-content/plugins/widgetkit/plugins/widgets/slidesetlightbox/views/WidgetkitExPlugin.php on line 354
Do you have any ideas how to solve it?

**Comment by rvalitov** [comment]
Hi! Thank you for reporting this. I will fix this issue in next release. Can you please look at the about screen of the widget and tell me if the widget correctly detects and shows version of WordPress there?

**Comment by thegiorgiok** [comment]
:)
Plugin name	SlidesetEx
Plugin version	v1.2.0
Plugin build date	19/01/2017
CMS	WordPress 4.7.3
Widgetkit version	2.9.2
Database version	2.0.0
jQuery version	1.12.4
UIkit version	2.27.2
UIkit version in Widgetkit bundle	2.27.2
Yootheme Pro compatible	Yes
AngularJS version	1.3.20
PHP version	7.0.16 (litespeed)
Installation path	/home/wildaroma/public_html/wp-content/plugins/widgetkit/plugins/widgets/slidesetlightbox
Write access check	Ok
Files integrity	Verify files
Author	Ramil Valitov
Website	https://github.com/rvalitov/widgetkit-slidesetlightbox
Wiki and manuals	https://github.com/rvalitov/widgetkit-slidesetlightbox/wiki
Your version of the plugin is up to date!

**Comment by rvalitov** [comment]
I made the patch. Please download the file from [here](https://mega.nz/#!TgNHTKbQ!dPWHSWXbVsnA0_8mvj3pO92UVt7gfAoDaY6q-Dl8Rz4), and replace the old file on your server with the new one. You can find the old file on your server in folder _/administrator/components/com_widgetkit/plugins/widgets/slidesetlightbox/views/_

After that please report about the results.

**Comment by thegiorgiok** [comment]
Hi, it looks good, no more php errors :)
link: http://wildaroma.gr/herbs-pet-jar/
the second gallery!
thanks for your time man!
