### ISSUE TITLE
plugin deleted after widgetkit update

### ISSUE THREAD

**Issue by rkleinert** [rvalitov/widgetkit-slidesetlightbox#8]
Hi,
after updating widgetkit the plugin was deleted. How can I avoid that?

Thanks,
Robert

**Comment by rvalitov** [comment]
Hi Robert!
Well, it should not be deleted, actually 😄 I updated widegetkit to version 2.9.17 myself on one of my websites yesterday and it was fine. I will try to help you to solve this issue. Can you please provide more information and answer to the questions below?

- what CMS (Joomla/Wordpress) do you use and its version?
- do you remember what version of widgetkit you had before the update?
- what version of the widgetkit you updated to?
- is it the first time you made the update, i.e. this problem occurred only now and did not exist when you made the updates in the past?
- was the widget installed in the administrator folder as written in the [manual](https://github.com/rvalitov/widgetkit-slidesetlightbox/wiki/How-to-install#for-joomla)?

**Comment by rvalitov** [comment]
@rkleinert I didn't get any updates from you. Does it mean that this issue is solved?

**Comment by rvalitov** [comment]
Closing, there's no answer from @rkleinert
