### ISSUE TITLE
Just first image is loading and Dotnav isn't showing

### ISSUE THREAD

**Issue by Klingelingeling** [rvalitov/widgetkit-slidesetlightbox#9]
Good evening,

As the email address seems to be inactive I try to report the issue here. Installed this great Widgetkit add-in under Joomla 3.8.10 with Yootheme Pro version 1.13.2 and Widgetkit version 2.9.18. Integration was really easy but when I try to show more than one picture in the Slideset it doesn't work. It just shows the first image. Media2 + 3 own defined media fields don't show up. As well the Dotnav navigation isn't visible.

Hopefully it can be fixed as this Widget would be great to use.

Cheers

**Comment by rvalitov** [comment]
Hi! Sorry, I didn't receive any of your emails.
As far as I understand, you want to display several items. In terms of Widgetkit each item can have one or several media fields, title, description and other fields. In this case, please, just add new items, and that's all - you don't need to invent/insert new media fields. My widget works exactly the same way as the standard widget, so if you have experience with standard widget, then you know how to add new items.

**Comment by Klingelingeling** [comment]
Hi Ramil

Thanks for your feedback. I followed your instructions in the Wiki -> https://github.com/rvalitov/widgetkit-slidesetlightbox/wiki/Media-content-fields But as described it just shows the picture which has been added in the standard media field. Other pictures in fields picture 2, picture 3 etc. will not be displayed. If I do this in the standard Grid Slider widget it’s working but then I don’t have the Lightbox feature.

Regards
Fabian

Von: Ramil Valitov <notifications@github.com>
Gesendet: Samstag, 28. Juli 2018 01:15
An: rvalitov/widgetkit-slidesetlightbox <widgetkit-slidesetlightbox@noreply.github.com>
Cc: Fabian Nussbaumer <fabian.nussbaumer@enovate.ch>; Author <author@noreply.github.com>
Betreff: Re: [rvalitov/widgetkit-slidesetlightbox] Just first image is loading and Dotnav isn't showing (#9)


Hi! Sorry, I didn't receive any of your emails.
As far as I understand, you want to display several items. In terms of Widgetkit each item can have one or several media fields, title, description and other fields. In this case, please, just add new items, and that's all - you don't need to invent/insert new media fields. My widget works exactly the same way as the standard widget, so if you have experience with standard widget, then you know how to add new items.

**Comment by rvalitov** [comment]
Please, provide administrator access to Joomla's backend, so I can investigate the issue. Please, send the credentials to ramilvalitov@gmail.com

**Comment by Klingelingeling** [comment]
Hi Ramil

I prefer to not handout administrative rights. Hope you understand it. I’m appreciated with your support and will donate if I can use your Widget on the website of my customer.

I figured out it was an issue with my Widgetkit installation. After reinstall Widgetkit it’s working properly.

But I’ve two other things I cannot figure out.

  *   Is it possible to have Slidenavs on the  media « thumbnails » ? See as example here -> https://www.siegrist-bau.ch/referenzen/

It’s possbile to navigate on the pictures and as well you can click on it to see it in a Lightbox.



  *   Another thing is that I’ve at the moment 3 items but with your Widget after two it makes a «second site ». I would like to show all, 2 on the first row and 1 on the second row. Is that possible ?

See here as reference what I’ve implemented with the Standard Grid Slider -> http://beta.bbu-ht.ch/referenzen.html

Regards
Fabian

Von: Ramil Valitov <notifications@github.com>
Gesendet: Sonntag, 29. Juli 2018 11:02
An: rvalitov/widgetkit-slidesetlightbox <widgetkit-slidesetlightbox@noreply.github.com>
Cc: Fabian Nussbaumer <fabian.nussbaumer@enovate.ch>; Author <author@noreply.github.com>
Betreff: Re: [rvalitov/widgetkit-slidesetlightbox] Just first image is loading and Dotnav isn't showing (#9)


Please, provide administrator access to Joomla's backend, so I can investigate the issue. Please, send the credentials to ramilvalitov@gmail.com<mailto:ramilvalitov@gmail.com>

**Comment by rvalitov** [comment]
Sure, I understand and respect your precaution regarding the access. I'm glad that you solved the problem by reinstalling the Widgetkit.

The answers to your questions are below:

>  Is it possible to have Slidenavs on the  media « thumbnails » ? See as example here -> https://www.siegrist-bau.ch/referenzen/

Yes, it's possible, but not with the current widget. [SlideshowEx](https://github.com/rvalitov/widgetkit-slideshow-ex) is exactly what you need: it shows a single image - a slide, one at a time. And you can navigate directly by clicking on the slide or through the Lightbox mode.

> Another thing is that I’ve at the moment 3 items but with your Widget after two it makes a «second site ». I would like to show all, 2 on the first row and 1 on the second row. Is that possible ?
> 
> See here as reference what I’ve implemented with the Standard Grid Slider -> http://beta.bbu-ht.ch/referenzen.html

Sorry, I don't understand what you mean. Can you please explain it or provide some screenshots? The link you provided does not work, I see a "Connection reset" error.

**Comment by Klingelingeling** [comment]
Hi Ramil,

Here’s the correct link.
https://www.bbu-ht.ch/referenzen.html

I would like to have the layout like this below. On a first row two items will be shown. On a second row the 3rd and probably 4th item, one a third row the 5th and 6th, etc.

[cid:image003.png@01D4290F.B3B35670]

Regards
Fabian



Von: Ramil Valitov <notifications@github.com>
Gesendet: Montag, 30. Juli 2018 21:23
An: rvalitov/widgetkit-slidesetlightbox <widgetkit-slidesetlightbox@noreply.github.com>
Cc: Fabian Nussbaumer <fabian.nussbaumer@enovate.ch>; Author <author@noreply.github.com>
Betreff: Re: [rvalitov/widgetkit-slidesetlightbox] Just first image is loading and Dotnav isn't showing (#9)


Sure, I understand and respect your precaution regarding the access. I'm glad that you solved the problem by reinstalling the Widgetkit.

The answers to your questions are below:

Is it possible to have Slidenavs on the media « thumbnails » ? See as example here -> https://www.siegrist-bau.ch/referenzen/

Yes, it's possible, but not with the current widget. SlideshowEx<https://github.com/rvalitov/widgetkit-slideshow-ex> is exactly what you need: it shows a single image - a slide, one at a time. And you can navigate directly by clicking on the slide or through the Lightbox mode.

Another thing is that I’ve at the moment 3 items but with your Widget after two it makes a «second site ». I would like to show all, 2 on the first row and 1 on the second row. Is that possible ?

See here as reference what I’ve implemented with the Standard Grid Slider -> http://beta.bbu-ht.ch/referenzen.html

Sorry, I don't understand what you mean. Can you please explain it or provide some screenshots? The link you provided does not work, I see a "Connection reset" error.

**Comment by rvalitov** [comment]
Thank you, now the link works. However, I don't understand your idea about the rows. As far as I understand, you use a grid, which you can configure as needed to display items per row. Please, provide some more details or a screenshot what you need.

**Comment by Klingelingeling** [comment]
Hi Ramil

Under https://www.bbu-ht.ch/referenzen.html it looks with the «original» widget like this below. 2 rows and 2 columns.
[cid:image003.jpg@01D42B71.02C39D20]

With your widget it’s just one column with two rows and below the dotnav to navigate to the «next page». But I would like to have like above. Is it possible?
[cid:image004.jpg@01D42B71.02C39D20]

Regards
Fabian

Von: Ramil Valitov <notifications@github.com>
Gesendet: Dienstag, 31. Juli 2018 23:06
An: rvalitov/widgetkit-slidesetlightbox <widgetkit-slidesetlightbox@noreply.github.com>
Cc: Fabian Nussbaumer <fabian.nussbaumer@enovate.ch>; Author <author@noreply.github.com>
Betreff: Re: [rvalitov/widgetkit-slidesetlightbox] Just first image is loading and Dotnav isn't showing (#9)


Thank you, now the link works. However, I don't understand your idea about the rows. As far as I understand, you use a grid, which you can configure as needed to display items per row. Please, provide some more details or a screenshot what you need.

**Comment by rvalitov** [comment]
Dear Fabian, in your last message I don't see any screenshots. May be it's a processing problem because you actually post in GitHub via emails. 

On the link provided you use a Grid with a standard Slideshow widget. Of course, you are free to use any widget inside the Grid, for example, SlideshowEx. In such case you can have as many rows and columns as you need. I hope that I understood your question correctly and my answer helps you.
